services:
  - type: web
    name: wonderful-editor
    env: ruby
    plan: free
    branch: main
    numInstances: 1
    healthCheckPath: /
    buildCommand: |
      bundle install
      # 本番でも devDependencies を入れる（--frozen-lockfile で失敗したら通常インストールにフォールバック）
      yarn install --frozen-lockfile --production=false || yarn install --production=false
      bundle exec rake assets:precompile
    startCommand: bundle exec puma -C config/puma.rb
    envVars:
      - key: RAILS_ENV
        value: production
      - key: NODE_ENV
        value: production
      - key: RAILS_LOG_TO_STDOUT
        value: "true"
      # devDependencies も入れるために必須
      - key: YARN_PRODUCTION
        value: "false"
      # （任意）ビルド安定化のための Yarn キャッシュ
      - key: YARN_CACHE_FOLDER
        value: /opt/render/.cache/yarn

databases:
  - name: postgresql-wonderful-editor
    region: singapore
    plan: free
    ipAllowList:
      - source: 0.0.0.0/0
        description: everywhere # 学習用